name: Update Lucide (PR)

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1'  # Mondays 06:00 UTC

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: update-lucide
  cancel-in-progress: false

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      DEFAULT_PY: "3.14"
      BRANCH_NAME: "chore/update-lucide"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.DEFAULT_PY }}

      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
          pip install tomlkit

      - name: Update Lucide icons
        run: |
          python download_lucide_icons.py

      - name: Detect changes (incl. untracked)
        id: changes
        run: |
          git add -A

          if git diff --cached --quiet; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
            echo "DEBUG: No staged changes detected:"
            git status --porcelain
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Bump version (patch)
        if: steps.changes.outputs.changed == 'true'
        id: bump
        run: |
          VERSION=$(python scripts/bump_version.py --type patch)
          echo "version=${VERSION}" >> "$GITHUB_OUTPUT"

      - name: Create/update PR
        if: steps.changes.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ env.BRANCH_NAME }}
          delete-branch: false
          title: "chore: update Lucide & bump version to v${{ steps.bump.outputs.version }}"
          body: |
            This automated PR updates Lucide icons and bumps the package version.

            - Updated icons via `download_lucide_icons.py`
            - Version bumped to **v${{ steps.bump.outputs.version }}** in `pyproject.toml`

            Merge when CI is green.
          commit-message: "chore: update Lucide icons & bump to v${{ steps.bump.outputs.version }}"
          labels: |
            dependencies
            automated
          signoff: false
          draft: false

      - name: No changes
        if: steps.changes.outputs.changed != 'true'
        run: echo "No Lucide update found. No PR created."
